$ANSIBLE_VAULT;1.1;AES256
37663831626337653263303564306163323938346664333039363837306464323466366535656663
6132653665616130316261636366303039336562346638320a623362643731633363373662636261
32633430333933633537666463336632626438386634356363333738323066353865346637393435
3261666163633262380a643962333961323533626434653636613935386665363030323862383536
37653361633434333931623964303039623338616433623061653431346236393463343533356562
34666262313334323830393632383061376335383630303461363438396437663339623439363030
37326364643639616131613365666133336339656134656562343934323031376666373566663932
36313138626566323735393835383332383933323939386237663764663636323231383537616232
65376166373164333734333533336538663862383866626161323061633635333336363134643531
64383565616431383466316437666637393534326139363432393666656333366561356531656339
38393166333837363533333265343830396339643432376461663038623439393937663937383863
63313335323334666661313231333637663531303662363231363737613638316539326137323365
65316461323761656133633266306133346364346462366633393365313662303539616363333236
35343438656331303062316231303861333565383366343737386163346530383362666264333366
35333462386238326137383132313765333532383762316462363638373633623432306466343439
66353461323263316334
